project = "homework-2-321920"
user_ip        = "31.202.20.192/32"
network_name   = "vpc-network"
script         = "startup-lamp"
sql-user       = "user"
sql-password   = "password"
ssh_public_key = "/home/ichijoint/.ssh/id_rsa.pub"